name: ntodo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  flutter_svg: ^2.0.9

  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.2
  flutter_bloc:
  bloc:
  get_it: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true



